version: "3"

services:
  db:
    image: postgres:latest
    container_name: db
    restart: unless-stopped
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB}
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
    networks:
      - default

  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: api
    links:
      - "db"
    restart: unless-stopped
    env_file: .env
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB=${DB}
      - PORT=${PORT}
    ports:
      - "${PORT}:3000"
    volumes:
      - .:/app
    depends_on:
      - db
    networks:
      - default

networks:
  default:

volumes:
  dbdata:
